/**
 * 
 */
package popl_formative;

/**
 * An exception to be thrown when a Semaphore wait count for a thread / value
 * has overflowed.
 * @author Thomas Wright <tdw511@york.ac.uk>
 *
 */
public class SemaphoreWaitOverflowException extends SemaphoreOverflowException {

	public SemaphoreWaitOverflowException() {
		super();
	}

	public SemaphoreWaitOverflowException(String string) {
		super(string);
	}

	/**
	 * An autogenerated serialisation version ID, allowing safe serialisation.
	 */
	private static final long serialVersionUID = -6707799256987366172L;
}
